---
project-name: aprd
pre-deploy: "mix ecto.migrate"
git-remote: git@github.com:artsy/apr-dashboard.git
hokusai-required-version: ">=0.5.8"
template-config-files:
  - s3://artsy-citadel/k8s/hokusai-vars.yml
