---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aprd-web
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aprd
        component: web
        layer: application
      name: aprd-web
    spec:
      containers:
      - name: aprd-web
        envFrom:
        - configMapRef:
            name: aprd-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/aprd:production
        imagePullPolicy: Always
        ports:
        - name: aprd-http
          containerPort: 8080
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aprd
    component: web
    layer: application
  name: aprd-web-internal
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: aprd
    layer: application
    component: web
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aprd
spec:
  rules:
    - host: aprd.artsy.net
      http:
        paths:
          - path: /
            backend:
              serviceName: aprd-web-internal
              servicePort: http

